In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [2]:
import tensorflow as tf

In [3]:
X_data = np.linspace(0.0 ,10.0 ,1000000)

In [4]:
X_data

array([0.000000e+00, 1.000001e-05, 2.000002e-05, ..., 9.999980e+00,
       9.999990e+00, 1.000000e+01])

In [5]:
noise = np.random.randn(len(X_data))

In [6]:
noise

array([-0.22293736, -1.1719916 ,  1.1485364 , ..., -0.996949  ,
        1.57626438, -0.14572983])

In [8]:
y= 0.5 * X_data +5 +noise

In [9]:
X_df = pd.DataFrame(X_data,columns= ["X Data"])
y_df = pd.DataFrame(y,columns=["Y"])

In [10]:
my_data =pd.concat([X_df,y_df],axis=1)

In [11]:
my_data

          X Data          Y
0        0.00000   4.777063
1        0.00001   3.828013
2        0.00002   6.148546
3        0.00003   4.934135
4        0.00004   6.085284
5        0.00005   5.382689
6        0.00006   3.399315
7        0.00007   6.475845
8        0.00008   5.148883
9        0.00009   5.069765
10       0.00010   5.706959
11       0.00011   4.683673
12       0.00012   3.140465
13       0.00013   5.887763
14       0.00014   5.118598
15       0.00015   4.399692
16       0.00016   7.133552
17       0.00017   5.327233
18       0.00018   5.074712
19       0.00019   3.879315
20       0.00020   4.939061
21       0.00021   6.232376
22       0.00022   5.655898
23       0.00023   4.165069
24       0.00024   5.665642
25       0.00025   4.515952
26       0.00026   5.490204
27       0.00027   4.415618
28       0.00028   4.826286
29       0.00029   5.007490
...          ...        ...
999970   9.99971   8.794444
999971   9.99972   9.966044
999972   9.99973  10.887027
999973   9.99974   8.837347
999974   9.99975   9.741743
999975   9.99976  10.226658
999976   9.99977  10.951988
999977   9.99978  11.845179
999978   9.99979   9.707885
999979   9.99980  10.656676
999980   9.99981   9.139225
999981   9.99982   9.793363
999982   9.99983   9.516927
999983   9.99984   9.477335
999984   9.99985  10.231531
999985   9.99986  10.612761
999986   9.99987  11.050208
999987   9.99988  11.313768
999988   9.99989   9.539943
999989   9.99990  10.359914
999990   9.99991  12.600979
999991   9.99992   8.259645
999992   9.99993   7.914582
999993   9.99994   8.993671
999994   9.99995   9.440567
999995   9.99996   9.138997
999996   9.99997  10.571140
999997   9.99998   9.003041
999998   9.99999  11.576259
999999  10.00000   9.854270

[1000000 rows x 2 columns]

In [12]:
m=tf.Variable(.81)
b=tf.Variable(0.17)

In [15]:
xph = tf.placeholder(tf.float32,[batch_size])
yph = tf.placeholder(tf.float32,[batch_size])

In [14]:
# Random 10 points to grab
batch_size = 8

In [16]:
y_model = m*xph + b

In [17]:
error = tf.reduce_sum(tf.square(yph-y_model))

In [18]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
train = optimizer.minimize(error)

In [19]:
init = tf.global_variables_initializer()